In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

data_file_path = "../data/final_0_80509.csv"

In [3]:
df = pd.read_csv(data_file_path,parse_dates=True, low_memory=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80510 entries, 0 to 80509
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   80510 non-null  int64
 1   AppID                   80510 non-null  int64
 2   Title                   78614 non-null  object
 3   Initial_Price           73639 non-null  float64
 4   Final_Price             73639 non-null  float64
 5   Discount_Percent        73639 non-null  float64
 6   Developers              75707 non-null  object
 7   Publishers              78618 non-null  object
 8   Genres                  75622 non-null  object
 9   Categories              75071 non-null  object
 10  Required_Age            78618 non-null  object
 11  Achievements            39397 non-null  float64
 12  Release_Date            78598 non-null  object
 13  Metacritic_score        3888 non-null   float64
 14  DLC_Flag                78618 non-null  object
 15  Win_Flag                78618 non-null  object
 16  Mac_Flag                78618 non-null  object
 17  Linux_Flag              78618 non-null  object
 18  OS                      73631 non-null  object
 19  Processor               71851 non-null  object
 20  Memory                  70594 non-null  object
 21  Graphics                63712 non-null  object
 22  DirectX                 39696 non-null  object
 23  Storage                 68323 non-null  object
 24  Current_Players         78952 non-null  float64
 25  Interface_Languages     80510 non-null  object
 26  Audio_Languages         80510 non-null  object
 27  Subtitle_Languages      80510 non-null  object
 28  Positive_Reviews        70727 non-null  object
 29  Negative_Reviews        70727 non-null  object
 30  Total_Reviews           68453 non-null  object
 31  Overall_Review_Summary  70727 non-null  object
 32  Recent_Reviews          5598 non-null   object
 33  Recent_Review_Summary   5598 non-null   object
 34  Mature_Content_Desc     10113 non-null  object
 35  Awards                  7 non-null      object
 36  Curators                65587 non-null  float64
dtypes: float64(7), int64(2), object(28)
memory usage: 22.7+ MB

In [4]:
df = df[["AppID","Title","Interface_Languages","Audio_Languages","Subtitle_Languages","Current_Players"]]
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80510 entries, 0 to 80509
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   AppID                80510 non-null  int64
 1   Title                78614 non-null  object
 2   Interface_Languages  80510 non-null  object
 3   Audio_Languages      80510 non-null  object
 4   Subtitle_Languages   80510 non-null  object
 5   Current_Players      78952 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 3.7+ MB

,AppID,Title,Interface_Languages,Audio_Languages,Subtitle_Languages,Current_Players
0,20200,Galactic Bowling,['English'],['English'],['English'],0.0
1,655370,Train Bandit,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],"['English', 'French', 'Italian', 'German', 'Sp...",0.0
2,1732930,Jolt Project,"['English', 'Portuguese - Brazil']",['English'],['English'],0.0
3,1355720,Henosis™,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],['English'],0.0
4,1139950,Two Weeks in Painland,"['English', 'Spanish - Spain']",['English'],"['English', 'Spanish - Spain']",0.0
5,1469160,Wartune Reborn,['English'],['English'],['English'],27.0
6,1659180,TD Worlds,"['English', 'Russian', 'Danish']",['English'],"['English', 'Russian', 'Danish']",0.0
7,1968760,Legend of Rome - The Wrath of Mars,"['English', 'German']","['English', 'German']","['English', 'German']",1.0
8,1178150,MazM: Jekyll and Hyde,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],"['English', 'French', 'Italian', 'German', 'Sp...",0.0
9,320150,Deadlings: Rotten Edition,"['English', 'Polish', 'French', 'Italian', 'Ge...",['English'],"['English', 'Polish', 'French', 'Italian', 'Ge...",0.0

In [5]:
df = df.dropna()
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77120 entries, 0 to 80509
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   AppID                77120 non-null  int64
 1   Title                77120 non-null  object
 2   Interface_Languages  77120 non-null  object
 3   Audio_Languages      77120 non-null  object
 4   Subtitle_Languages   77120 non-null  object
 5   Current_Players      77120 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.1+ MB

,AppID,Title,Interface_Languages,Audio_Languages,Subtitle_Languages,Current_Players
0,20200,Galactic Bowling,['English'],['English'],['English'],0.0
1,655370,Train Bandit,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],"['English', 'French', 'Italian', 'German', 'Sp...",0.0
2,1732930,Jolt Project,"['English', 'Portuguese - Brazil']",['English'],['English'],0.0
3,1355720,Henosis™,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],['English'],0.0
4,1139950,Two Weeks in Painland,"['English', 'Spanish - Spain']",['English'],"['English', 'Spanish - Spain']",0.0
5,1469160,Wartune Reborn,['English'],['English'],['English'],27.0
6,1659180,TD Worlds,"['English', 'Russian', 'Danish']",['English'],"['English', 'Russian', 'Danish']",0.0
7,1968760,Legend of Rome - The Wrath of Mars,"['English', 'German']","['English', 'German']","['English', 'German']",1.0
8,1178150,MazM: Jekyll and Hyde,"['English', 'French', 'Italian', 'German', 'Sp...",['English'],"['English', 'French', 'Italian', 'German', 'Sp...",0.0
9,320150,Deadlings: Rotten Edition,"['English', 'Polish', 'French', 'Italian', 'Ge...",['English'],"['English', 'Polish', 'French', 'Italian', 'Ge...",0.0

In [25]:
def count_languages_length(languages_str):
    languages_list = languages_str.split(',')
    return len(languages_list)

df['Audio_Languages_Length'] = df['Audio_Languages'].apply(count_languages_length)
df['Interface_Languages_Length'] = df['Interface_Languages'].apply(count_languages_length)
df['Subtitle_Languages_Length'] = df['Subtitle_Languages'].apply(count_languages_length)

df['Total_Languages_Count'] = df['Interface_Languages_Length'] + df['Audio_Languages_Length'] + df['Subtitle_Languages_Length']
non_zero_players = df['Current_Players']!=0
correlation = df['Total_Languages_Count'].corr(non_zero_players)
print(correlation)
print(non_zero_players.head(10))

0.044260917954336974
0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8    False
9    False
Name: Current_Players, dtype: bool

In [70]:
# print(non_zero_players)
# # skip = None
# # current_players_x = df[(df['Current_Players']!=0)]
# # total_lang = df[df["AppID"].isin(current_players_x["AppID"])]
# # subtitle_language_y = df[df["Current_Players"].isin(current_players_x["Current_Players"])]
# # plt.bar(current_players_x['Current_Players'],total_lang['Total_Languages_Count'],label='Language Variety Analysis',color = 'red')
# # plt.xticks(rotation=90)
# # plt.xlabel('No of Players',fontsize = 15)
# # plt.ylabel('Language Variety',fontsize = 15)
# # plt.title('Language Variety Impact on Number of Players')
# # plt.legend(loc = 1, fontsize = 15)
# # plt.show()

         AppID                                              Title  \
5      1469160                                     Wartune Reborn
7      1968760                 Legend of Rome - The Wrath of Mars
10     1026420                      WARSAW RISING: City of Heroes
14     1454010                                     Diary of Lucie
17      346560                             Hero of the Kingdom II
...        ...                                                ...
80440  1287290                                  WolfTeam: Classic
80459  1222580                                         Rustissimo
80474  2238430  Mon-Yu: Defeat Monsters And Gain Strong Weapon...
80481  2295410                       Ragnarok Survivors: Valhalla
80509  2491770            We Need To Cook - Drug Empire Simulator

                                     Interface_Languages  \
5                                            ['English']
7                                  ['English', 'German']
10     ['English', 'French', 'German', 'Polish', 'Rus...
14                                 ['English', 'Korean']
17     ['English', 'French', 'German', 'Spanish - Spa...
...                                                  ...
80440  ['English', 'Arabic', 'Spanish - Latin America...
80459                                        ['English']
80474                            ['English', 'Japanese']
80481                                        ['English']
80509                                        ['English']

             Audio_Languages  \
5                ['English']
7      ['English', 'German']
10                ['Polish']
14               ['English']
17               ['English']
...                      ...
80440            ['English']
80459            ['English']
80474           ['Japanese']
80481            ['English']
80509            ['English']

                                      Subtitle_Languages  Current_Players  \
5                                            ['English']             27.0
7                                  ['English', 'German']              1.0
10     ['English', 'French', 'German', 'Polish', 'Rus...              6.0
14                                 ['English', 'Korean']              2.0
17                                           ['English']              3.0
...                                                  ...              ...
80440                                        ['English']             26.0
80459                                        ['English']              4.0
80474                            ['English', 'Japanese']              2.0
80481                                        ['English']              1.0
80509                                        ['English']              3.0

       Audio_Languages_Length  Interface_Languages_Length  \
5                           1                           1
7                           2                           2
10                          1                           5
14                          1                           2
17                          1                          16
...                       ...                         ...
80440                       1                           4
80459                       1                           1
80474                       1                           2
80481                       1                           1
80509                       1                           1

       Subtitle_Languages_Length  Total_Languages_Count
5                              1                      3
7                              2                      6
10                             5                     11
14                             2                      5
17                             1                     18
...                          ...                    ...
80440                          1                      6
80459                          1                      3
80474                          2                      5
80481                          1                      3
80509                          1                      3

[14488 rows x 10 columns]