In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/final_0_80509.csv")
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\3731924929.py:1: DtypeWarning: Columns (10,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/final_0_80509.csv")

,Index,AppID,Title,Initial_Price,Final_Price,Discount_Percent,Developers,Publishers,Genres,Categories,...,Subtitle_Languages,Positive_Reviews,Negative_Reviews,Total_Reviews,Overall_Review_Summary,Recent_Reviews,Recent_Review_Summary,Mature_Content_Desc,Awards,Curators
0,0,20200,Galactic Bowling,NaN,NaN,NaN,['Perpetual FX Creative'],['Perpetual FX Creative'],"['Casual', 'Indie', 'Sports']","['Single-player', 'Multi-player', 'Steam Achie...",...,['English'],6,11,12,Mostly Negative,NaN,NaN,NaN,NaN,6.0
1,1,655370,Train Bandit,52.0,52.0,0.0,['Rusty Moyher'],['Wild Rooster'],"['Action', 'Indie']","['Single-player', 'Steam Achievements', 'Full ...",...,"['English', 'French', 'Italian', 'German', 'Sp...",57,7,53,Very Positive,NaN,NaN,NaN,NaN,8.0
2,2,1732930,Jolt Project,199.0,199.0,0.0,['Campião Games'],['Campião Games'],"['Action', 'Adventure', 'Indie', 'Strategy']",['Single-player'],...,['English'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,3,1355720,Henosis™,NaN,NaN,NaN,['Odd Critter Games'],['Odd Critter Games'],"['Adventure', 'Casual', 'Indie']","['Single-player', 'Full controller support']",...,['English'],5,0,5,5 user reviews,NaN,NaN,NaN,NaN,5.0
4,4,1139950,Two Weeks in Painland,0.0,0.0,0.0,['Unusual Games'],['Unusual Games'],"['Adventure', 'Indie']","['Single-player', 'Steam Achievements']",...,"['English', 'Spanish - Spain']",53,6,59,Very Positive,NaN,NaN,This Game may contain content not appropriate ...,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80505,80505,574674,VRC PRO Deluxe Off-road tracks 4,570.0,285.0,50.0,['Virtual Racing Industries Ltd.'],['Virtual Racing Industries Ltd.'],"['Action', 'Casual', 'Indie', 'Racing', 'Simul...","['Single-player', 'Multi-player', 'Downloadabl...",...,['English'],0,1,1,1 user reviews,NaN,NaN,NaN,NaN,NaN
80506,80506,947930,Car Mechanic Simulator 2018 - Porsche DLC,300.0,36.0,88.0,['Red Dot Games'],['PlayWay S.A.'],"['Racing', 'Simulation']","['Single-player', 'Downloadable Content', 'Ste...",...,"['English', 'French', 'Italian', 'German', 'Sp...",67,7,70,Very Positive,NaN,NaN,NaN,NaN,1.0
80507,80507,1900780,Erannorth Chronicles - Ancient Ruins,450.0,360.0,20.0,['Spyridon Thalassinos'],['Spyridon Thalassinos'],"['Adventure', 'Indie', 'RPG', 'Strategy']","['Single-player', 'Downloadable Content', 'Ste...",...,['English'],10,0,10,Positive,NaN,NaN,NaN,NaN,NaN
80508,80508,2470521,Crossout — Electric beetle (Lite edition),1199.0,1199.0,0.0,['Targem Games'],['Gaijin Distribution KFT'],"['Action', 'Free to Play', 'Massively Multipla...","['Multi-player', 'MMO', 'PvP', 'Online PvP', '...",...,['English'],3,19,21,Negative,NaN,NaN,NaN,NaN,NaN
80509,80509,2491770,We Need To Cook - Drug Empire Simulator,480.0,480.0,0.0,"['Anark Studios', 'Crowbar Games']","['Anark Studios', 'Crowbar Games']","['Action', 'Adventure', 'Indie', 'Simulation',...",['Single-player'],...,['English'],30,16,42,Mixed,18,Mixed,The mature content featured pertains to drug u...,NaN,4.0

In [4]:
df.columns

Index(['Index', 'AppID', 'Title', 'Initial_Price', 'Final_Price',
       'Discount_Percent', 'Developers', 'Publishers', 'Genres', 'Categories',
       'Required_Age', 'Achievements', 'Release_Date', 'Metacritic_score',
       'DLC_Flag', 'Win_Flag', 'Mac_Flag', 'Linux_Flag', 'OS', 'Processor',
       'Memory', 'Graphics', 'DirectX', 'Storage', 'Current_Players',
       'Interface_Languages', 'Audio_Languages', 'Subtitle_Languages',
       'Positive_Reviews', 'Negative_Reviews', 'Total_Reviews',
       'Overall_Review_Summary', 'Recent_Reviews', 'Recent_Review_Summary',
       'Mature_Content_Desc', 'Awards', 'Curators'],
      dtype='object')

In [5]:
good_df = df[["Initial_Price", "Final_Price" , "Required_Age" , 'Win_Flag', 'Mac_Flag', 'Linux_Flag',"Memory","Storage","Positive_Reviews" , "Negative_Reviews","Overall_Review_Summary"]]
good_df

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary
0,NaN,NaN,0,True,False,False,512 MB,NaN,6,11,Mostly Negative
1,52.0,52.0,0,True,True,False,1 GB,50 MB,57,7,Very Positive
2,199.0,199.0,0,True,False,False,250 MB,202 MB,NaN,NaN,NaN
3,NaN,NaN,0,True,True,True,2 GB,2500 MB,5,0,5 user reviews
4,0.0,0.0,0,True,True,False,2 GB,3 GB,53,6,Very Positive
...,...,...,...,...,...,...,...,...,...,...,...
80505,570.0,285.0,0,True,False,False,1 GB,2 GB,0,1,1 user reviews
80506,300.0,36.0,0,True,True,False,4 GB,20 GB,67,7,Very Positive
80507,450.0,360.0,0,True,False,False,6 GB,6 GB,10,0,Positive
80508,1199.0,1199.0,0,True,False,False,4 GB,12 GB,3,19,Negative
80509,480.0,480.0,0,True,False,False,5 GB,5 GB,30,16,Mixed

1. initial / final
2. Required_Age
3. 'Win_Flag', 'Mac_Flag', 'Linux_Flag'
4. mem and storage 
5. +ve, -ve, 

target
overall_review_sumary

In [6]:
classified = good_df[~good_df["Overall_Review_Summary"].isna()]
classified

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary
0,NaN,NaN,0,True,False,False,512 MB,NaN,6,11,Mostly Negative
1,52.0,52.0,0,True,True,False,1 GB,50 MB,57,7,Very Positive
3,NaN,NaN,0,True,True,True,2 GB,2500 MB,5,0,5 user reviews
4,0.0,0.0,0,True,True,False,2 GB,3 GB,53,6,Very Positive
5,0.0,0.0,0,True,False,False,2 GB,100 MB,133,69,Mixed
...,...,...,...,...,...,...,...,...,...,...,...
80505,570.0,285.0,0,True,False,False,1 GB,2 GB,0,1,1 user reviews
80506,300.0,36.0,0,True,True,False,4 GB,20 GB,67,7,Very Positive
80507,450.0,360.0,0,True,False,False,6 GB,6 GB,10,0,Positive
80508,1199.0,1199.0,0,True,False,False,4 GB,12 GB,3,19,Negative
80509,480.0,480.0,0,True,False,False,5 GB,5 GB,30,16,Mixed

In [7]:
discard = [np.nan, '5 user reviews', 
       '1 user reviews',  '6 user reviews',
       '3 user reviews', '8 user reviews', 'No user reviews',
       '4 user reviews',  
       '2 user reviews', '9 user reviews', '7 user reviews',
       ]
good_classified = classified[~classified["Overall_Review_Summary"].isin(discard)]
good_classified

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary
0,NaN,NaN,0,True,False,False,512 MB,NaN,6,11,Mostly Negative
1,52.0,52.0,0,True,True,False,1 GB,50 MB,57,7,Very Positive
4,0.0,0.0,0,True,True,False,2 GB,3 GB,53,6,Very Positive
5,0.0,0.0,0,True,False,False,2 GB,100 MB,133,69,Mixed
6,530.0,530.0,0,True,False,False,2 GB,500 MB,22,9,Mixed
...,...,...,...,...,...,...,...,...,...,...,...
80504,299.0,299.0,0,True,False,False,8 GB,25 GB,5,8,Mostly Negative
80506,300.0,36.0,0,True,True,False,4 GB,20 GB,67,7,Very Positive
80507,450.0,360.0,0,True,False,False,6 GB,6 GB,10,0,Positive
80508,1199.0,1199.0,0,True,False,False,4 GB,12 GB,3,19,Negative
80509,480.0,480.0,0,True,False,False,5 GB,5 GB,30,16,Mixed

In [8]:
bad_classified = classified[(classified["Overall_Review_Summary"].isin(discard) & ~classified["Positive_Reviews"].isna() & ~classified["Negative_Reviews"].isna())]
bad_classified

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary
3,NaN,NaN,0,True,True,True,2 GB,2500 MB,5,0,5 user reviews
7,349.0,349.0,0,True,False,False,1 GB,300 MB,1,0,1 user reviews
12,85.0,85.0,0,True,False,False,NaN,100 MB,7,0,6 user reviews
19,349.0,349.0,0,True,False,False,2 GB,100 MB,3,1,3 user reviews
23,125.0,125.0,0,True,False,False,2 GB,60 MB,6,10,1 user reviews
...,...,...,...,...,...,...,...,...,...,...,...
80491,349.0,349.0,0,True,True,False,1 GB,1 GB,2,1,3 user reviews
80498,1300.0,1300.0,0,True,False,False,8 GB,NaN,2,0,2 user reviews
80499,164.0,164.0,0,True,False,False,4 GB,20 GB,8,1,8 user reviews
80502,610.0,610.0,0,True,False,False,4 GB,3 GB,1,0,No user reviews
80505,570.0,285.0,0,True,False,False,1 GB,2 GB,0,1,1 user reviews

In [9]:
# target assign
def assign_target(row):
    if row["Overall_Review_Summary"] is  np.nan:
        return np.nan
    
    summary = row["Overall_Review_Summary"].lower()
    if "positive" in summary:
        return 1
    elif "negative" in summary:
        return -1
    elif "mixed" in summary:
        return 0
    
    p = row["Positive_Reviews"]
    n = row["Negative_Reviews"]

    if p > n:
        return 1
    elif p < n: 
        return -1
    return 0

good_classified["target"] = good_classified.apply(assign_target,axis=1)
good_classified

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\380241893.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good_classified["target"] = good_classified.apply(assign_target,axis=1)

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary,target
0,NaN,NaN,0,True,False,False,512 MB,NaN,6,11,Mostly Negative,-1
1,52.0,52.0,0,True,True,False,1 GB,50 MB,57,7,Very Positive,1
4,0.0,0.0,0,True,True,False,2 GB,3 GB,53,6,Very Positive,1
5,0.0,0.0,0,True,False,False,2 GB,100 MB,133,69,Mixed,0
6,530.0,530.0,0,True,False,False,2 GB,500 MB,22,9,Mixed,0
...,...,...,...,...,...,...,...,...,...,...,...,...
80504,299.0,299.0,0,True,False,False,8 GB,25 GB,5,8,Mostly Negative,-1
80506,300.0,36.0,0,True,True,False,4 GB,20 GB,67,7,Very Positive,1
80507,450.0,360.0,0,True,False,False,6 GB,6 GB,10,0,Positive,1
80508,1199.0,1199.0,0,True,False,False,4 GB,12 GB,3,19,Negative,-1
80509,480.0,480.0,0,True,False,False,5 GB,5 GB,30,16,Mixed,0

In [10]:
bad_classified["target"] = bad_classified.apply(assign_target, axis=1)
bad_classified

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\2805256452.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_classified["target"] = bad_classified.apply(assign_target, axis=1)

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary,target
3,NaN,NaN,0,True,True,True,2 GB,2500 MB,5,0,5 user reviews,1
7,349.0,349.0,0,True,False,False,1 GB,300 MB,1,0,1 user reviews,1
12,85.0,85.0,0,True,False,False,NaN,100 MB,7,0,6 user reviews,1
19,349.0,349.0,0,True,False,False,2 GB,100 MB,3,1,3 user reviews,1
23,125.0,125.0,0,True,False,False,2 GB,60 MB,6,10,1 user reviews,1
...,...,...,...,...,...,...,...,...,...,...,...,...
80491,349.0,349.0,0,True,True,False,1 GB,1 GB,2,1,3 user reviews,1
80498,1300.0,1300.0,0,True,False,False,8 GB,NaN,2,0,2 user reviews,1
80499,164.0,164.0,0,True,False,False,4 GB,20 GB,8,1,8 user reviews,1
80502,610.0,610.0,0,True,False,False,4 GB,3 GB,1,0,No user reviews,1
80505,570.0,285.0,0,True,False,False,1 GB,2 GB,0,1,1 user reviews,-1

In [11]:
final_df = pd.concat([good_classified,bad_classified])
final_df

,Initial_Price,Final_Price,Required_Age,Win_Flag,Mac_Flag,Linux_Flag,Memory,Storage,Positive_Reviews,Negative_Reviews,Overall_Review_Summary,target
0,NaN,NaN,0,True,False,False,512 MB,NaN,6,11,Mostly Negative,-1
1,52.0,52.0,0,True,True,False,1 GB,50 MB,57,7,Very Positive,1
4,0.0,0.0,0,True,True,False,2 GB,3 GB,53,6,Very Positive,1
5,0.0,0.0,0,True,False,False,2 GB,100 MB,133,69,Mixed,0
6,530.0,530.0,0,True,False,False,2 GB,500 MB,22,9,Mixed,0
...,...,...,...,...,...,...,...,...,...,...,...,...
80491,349.0,349.0,0,True,True,False,1 GB,1 GB,2,1,3 user reviews,1
80498,1300.0,1300.0,0,True,False,False,8 GB,NaN,2,0,2 user reviews,1
80499,164.0,164.0,0,True,False,False,4 GB,20 GB,8,1,8 user reviews,1
80502,610.0,610.0,0,True,False,False,4 GB,3 GB,1,0,No user reviews,1
80505,570.0,285.0,0,True,False,False,1 GB,2 GB,0,1,1 user reviews,-1

### Memory and storage process

In [12]:
final_df.dropna(inplace=True,subset=["Memory","Storage"])

In [13]:
import re


def extract_number(num : str):
    return float(re.sub(',' , '' , num))

def extract_memory_or_storage(num : str):
    try:
        n,unit = num.split()

        if unit == 'GB':
            return int(n) * 1024
        elif unit == 'MB':
            return int(n)
        return 0
    except:
        print(num)
# Parsing storage and memory

def filter_fn(row):

    if len(row["Memory"].split()) == 2 and len(row["Storage"].split()) == 2:
        return True
    return False

m = final_df.apply(filter_fn, axis=1)
data = final_df[m]
data["Memory_MB"] =  data["Memory"].apply(extract_memory_or_storage)
data["Storage_MB"] =  data["Storage"].apply(extract_memory_or_storage)
data.drop(["Memory" ,"Storage","Overall_Review_Summary"],axis=1,inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\3669446147.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Memory_MB"] =  data["Memory"].apply(extract_memory_or_storage)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\3669446147.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Storage_MB"] =  data["Storage"].apply(extract_memory_or_storage)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\3669446147.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(["Memory" ,"Storage","Overall_Review_Summary"],axis=1,inplace=True)

In [28]:
# data.to_csv("processed.csv",header=True,index=False)

## Reviews AND Flags parsing

In [27]:
# data["Positive_Reviews"] = data["Positive_Reviews"].apply(extract_number)
# data["Negative_Reviews"] = data["Negative_Reviews"].apply(extract_number)

data.Win_Flag = data.Win_Flag.astype(bool)
data.Mac_Flag = data.Mac_Flag.astype(bool)
data.Linux_Flag = data.Linux_Flag.astype(bool)
data.Required_Age = data.Required_Age.astype(float)
data.dtypes

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\1725034132.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Win_Flag = data.Win_Flag.astype(bool)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\1725034132.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Mac_Flag = data.Mac_Flag.astype(bool)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\1725034132.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Linux_Flag = data.Linux_Flag.astype(bool)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5728\1725034132.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Required_Age = data.Required_Age.astype(float)

Initial_Price       float64
Final_Price         float64
Required_Age        float64
Win_Flag               bool
Mac_Flag               bool
Linux_Flag             bool
Positive_Reviews    float64
Negative_Reviews    float64
target                int64
Memory_MB            uint64
Storage_MB           uint64
dtype: object

In [16]:
y = data["target"]
X = data.drop(["target"],axis=1)

In [17]:
# 
# +ve, mixed , -ve 
#   1     0     -1
df["Overall_Review_Summary"].unique()

array(['Mostly Negative', 'Very Positive', nan, '5 user reviews', 'Mixed',
       '1 user reviews', 'Mostly Positive', '6 user reviews', 'Positive',
       '3 user reviews', '8 user reviews', 'No user reviews',
       '4 user reviews', 'Negative', 'Overwhelmingly Positive',
       '2 user reviews', '9 user reviews', '7 user reviews',
       'Overwhelmingly Negative', 'Very Negative'], dtype=object)